apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rajeshkanimata/kubernetes-ingress-deployment.git'
    targetRevision: HEAD
    path: ARGOCD/INGRESS
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
